/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlinx.coroutines.*
import java.net.HttpURLConnection
import java.net.URL
import kotlin.time.measureTime

data class FetchResult(val url: String, val statusCode: Int, val elapsedMs: Long)

sealed class FetchOutcome {
    data class Success(val result: FetchResult) : FetchOutcome()
    data class Failure(val url: String, val error: Throwable): FetchOutcome()
}

suspend fun fetchUrl(url: String): FetchOutcome = withContext(Dispatchers.IO) {
    var statusCode = -1
    var caughtError: Exception? = null
    val duration = measureTime {
        val connection = URL(url).openConnection() as HttpURLConnection
        connection.requestMethod = "GET"
        connection.connectTimeout = 5_000
        connection.readTimeout = 5_000
        try {
            statusCode = connection.responseCode
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            caughtError = e
        } finally {
            connection.disconnect()
        }
    }

    caughtError?.let {
        FetchOutcome.Failure(url, it)
    } ?: FetchOutcome.Success(FetchResult(url, statusCode, duration.inWholeMilliseconds))
}

suspend fun main() = coroutineScope {
    val urls = listOf(
        "https://www.google.com",
        "https://www.github.com",
        "https://kotlinlang.org",
        "https://www.wikipedia.org",
        "https://httpbin.org/delay/1"
    )

    println("Fetching ${urls.size} URLs concurrently...\n")

    val totalTime = measureTime {
        // async를 먼저 다 시작시켜서 동시에 진행되게 함
        val deferredResults = urls.map { url ->
            async { fetchUrl(url) }
        }

        // await은 나중에 몰아서 — 이미 다 병렬로 돌고 있는 상태
        val outcomes = deferredResults.awaitAll()

        outcomes.forEach { outcome ->
            when (outcome) {
                is FetchOutcome.Success -> println("[${outcome.result.statusCode}] ${outcome.result.url} - ${outcome.result.elapsedMs}ms")
                is FetchOutcome.Failure -> println("[FAILED] ${outcome.url} - ${outcome.error.message}")
            }
        }
    }

    println("\nTotal time: ${totalTime.inWholeMilliseconds}ms")
}
