/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlinx.coroutines.*
import java.net.HttpURLConnection
import java.net.URL
import kotlin.time.measureTime

data class FetchResult(val url: String, val statusCode: Int, val elapsedMs: Long)

suspend fun fetchUrl(url: String): FetchResult = withContext(Dispatchers.IO) {
    var statusCode = -1
    val duration = measureTime {
        val connection = URL(url).openConnection() as HttpURLConnection
        connection.requestMethod = "GET"
        connection.connectTimeout = 5_000
        connection.readTimeout = 5_000
        try {
            statusCode = connection.responseCode
        } finally {
            connection.disconnect()
        }
    }
    FetchResult(url, statusCode, duration.inWholeMilliseconds)
}

suspend fun main() = coroutineScope {
    val urls = listOf(
        "https://www.google.com",
        "https://www.github.com",
        "https://kotlinlang.org",
        "https://www.wikipedia.org",
        "https://httpbin.org/delay/1"
    )

    println("Fetching ${urls.size} URLs concurrently...\n")

    val totalTime = measureTime {
        // async를 먼저 다 시작시켜서 동시에 진행되게 함
        val deferredResults = urls.map { url ->
            async { fetchUrl(url) }
        }

        // await은 나중에 몰아서 — 이미 다 병렬로 돌고 있는 상태
        val results = deferredResults.awaitAll()

        results.forEach { result ->
            println("[${result.statusCode}] ${result.url} - ${result.elapsedMs}ms")
        }
    }

    println("\nTotal time: ${totalTime.inWholeMilliseconds}ms")
}
